[package]
name = "UFC_NFT"
version = "1.0.0"
authors = []

[addresses]
UFC_NFT = "0x70c3a99237fe6e34da53a324b53685aeffb20c09b35681eb32c7718bd36179dc"
aptos_token_objects = "0x4"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"